# Github Actions 下载脚本配置
version: '2.0'

dir_rule:
  base_dir: ./album
#   rule: Bd_Atitle_Pindex

client:
  impl: html

  # domain:
  #   - 18comic.vip
  #   - 18comic.org
  #   - jm-comic.org
  #   - jm-comic2.cc

  postman:
    meta_data:
      # 使用系统代理，默认clash端口
      proxies: 
        http: http://127.0.0.1:7890
        https: http://127.0.0.1:7890
  #     # 如果需要登录，在这里配置cookies
  #     cookies: null

download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 45